service: serverless-image-resizer

provider:
  name: aws
  runtime: nodejs4.3
  region: ${env:AWS_REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
      Resource: "*"

functions:
  imageResizer:
    handler: index.handle
    environment:
      RESIZE_OPTION: ${env:RESIZE_OPTION}
      DEST_S3_BUCKET_NAME: ${env:DEST_S3_BUCKET_NAME}
      DEST_S3_PREFIX: ${env:DEST_S3_PREFIX}
    events:
      - s3:
          bucket: ${env:SOURCE_S3_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${env:SOURCE_S3_PREFIX}

resources:
  Resources:
    DestImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:DEST_S3_BUCKET_NAME}
